In [114]:
TEST_SIZE = 0.2
SEED = 4

In [115]:
import sys
IN_COLAB = 'google.colab' in sys.modules

if IN_COLAB:
  from google.colab import userdata
  from google.colab import drive
  drive.mount('/content/drive')
  PROJECT_ROOT = userdata.get('PROJECT_ROOT')
else:
  PROJECT_ROOT = '..'
  SRC = f"{PROJECT_ROOT}/src"
  if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)
  if SRC not in sys.path:
    sys.path.append(SRC)

In [116]:
import duckdb
import pandas as pd
import numpy as np
from pathlib import Path
from src.config import Config

LOCAL_MIMIC_DB = f"{PROJECT_ROOT}/{Config.DATA_DIR}/mimic_local.db"
conn = duckdb.connect(database=LOCAL_MIMIC_DB)

In [117]:
def load_query(file_path: str) -> str:
  with open(file_path, 'r') as f:
    return f.read()

# Exploration

In [118]:
MIMIC_PATH = f"{PROJECT_ROOT}/{Config.DATA_DIR}/mimic_iv/physionet.org/files/mimiciv/3.1"
MIMIC_ICU_PATH = f"{MIMIC_PATH}/icu"
MIMIC_HOSP_PATH = f"{MIMIC_PATH}/hosp"

In [119]:
d_items_df = pd.read_csv(f'{MIMIC_ICU_PATH}/d_items.csv.gz')
# item_filter = (d_items_df['label'].str.lower().str.contains("asopressin"))
item_filter = (d_items_df['itemid'] == 223761)
# item_filter = (d_items_df['linksto'] == "outputevents")
# item_filter = (d_items_df['category'] == "Dialysis")
d_items_df[item_filter]

,itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue
337,223761,Temperature Fahrenheit,Temperature F,chartevents,Routine Vital Signs,°F,Numeric,NaN,NaN

In [120]:
labitems_df = pd.read_csv(f'{MIMIC_HOSP_PATH}/d_labitems.csv.gz')
lab_filter = (labitems_df['itemid'] == 50885)
labitems_df[lab_filter]

    itemid             label  fluid   category
83   50885  Bilirubin, Total  Blood  Chemistry

# Cohort extraction

## Exclusions and target definition

In [121]:
cohort_query = load_query("mimic_queries/select_cohort.sql")

final_cohort = conn.execute(cohort_query).df()

conn.register("cohort", final_cohort)

print(f"Final Cohort: {final_cohort.shape[0]}")
print(f"Ethnic proportions: {final_cohort["race"].value_counts(normalize=True)}")
print(f"Case cohort: {final_cohort['target_noaf'].sum()}")
print(f"Control cohort: {final_cohort.shape[0] - final_cohort['target_noaf'].sum()}")

Final Cohort: 19480
Ethnic proportions: race
WHITE                                        0.574076
UNKNOWN                                      0.135883
BLACK/AFRICAN AMERICAN                       0.083676
OTHER                                        0.037988
UNABLE TO OBTAIN                             0.030082
WHITE - OTHER EUROPEAN                       0.019713
ASIAN                                        0.013296
HISPANIC/LATINO - PUERTO RICAN               0.012423
ASIAN - CHINESE                              0.011191
HISPANIC/LATINO - DOMINICAN                  0.009600
BLACK/CARIBBEAN ISLAND                       0.008316
HISPANIC OR LATINO                           0.008008
WHITE - RUSSIAN                              0.006571
BLACK/CAPE VERDEAN                           0.006520
PATIENT DECLINED TO ANSWER                   0.005647
BLACK/AFRICAN                                0.005493
PORTUGUESE                                   0.003953
ASIAN - SOUTH EAST ASIAN                     0.003901
ASIAN - ASIAN INDIAN                         0.002772
HISPANIC/LATINO - GUATEMALAN                 0.002567
HISPANIC/LATINO - SALVADORAN                 0.002464
WHITE - BRAZILIAN                            0.002413
AMERICAN INDIAN/ALASKA NATIVE                0.002310
WHITE - EASTERN EUROPEAN                     0.002310
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER    0.001386
HISPANIC/LATINO - MEXICAN                    0.001283
SOUTH AMERICAN                               0.001283
HISPANIC/LATINO - HONDURAN                   0.001078
ASIAN - KOREAN                               0.000873
HISPANIC/LATINO - CENTRAL AMERICAN           0.000821
MULTIPLE RACE/ETHNICITY                      0.000770
HISPANIC/LATINO - COLUMBIAN                  0.000770
HISPANIC/LATINO - CUBAN                      0.000565
Name: proportion, dtype: float64
Case cohort: 1494
Control cohort: 17986

## Feature extraction

### Vitals

In [122]:
vitals_query = load_query("mimic_queries/extract_vitals.sql")
df_vitals = conn.execute(vitals_query).df()

### Lab measurements

In [123]:
labs_query = load_query("mimic_queries/extract_lab_measurements.sql")
df_labs = conn.execute(labs_query).df()

### Urine output

In [124]:
urine_query = load_query("mimic_queries/extract_urine_outputs.sql")
df_urine = conn.execute(urine_query).df()

### Interventions

In [125]:
interventions_query = load_query("mimic_queries/extract_interventions.sql")
df_interventions = conn.execute(interventions_query).df()

### Comorbidities

In [126]:
comorbidities_query = load_query("mimic_queries/extract_comorbidities.sql")
df_comorbidities = conn.execute(comorbidities_query).df()

# Full cohort and features

In [127]:
dataset = final_cohort.merge(df_vitals, on="stay_id", how="left")
dataset = dataset.merge(df_labs, on="stay_id", how="left")
dataset = dataset.merge(df_urine, on="stay_id", how="left")
dataset = dataset.merge(df_interventions, on="stay_id", how="left")
dataset = dataset.merge(df_comorbidities, on="hadm_id", how="left")

comorb_cols = [col for col in dataset.columns if col.startswith('comorb_')]
dataset[comorb_cols] = dataset[comorb_cols].fillna(0).astype(int)

print(dataset.describe().T.to_markdown())

|                         |   count | mean                       | min                 | 25%                        | 50%                 | 75%                        | max                 |             std |
|:------------------------|--------:|:---------------------------|:--------------------|:---------------------------|:--------------------|:---------------------------|:--------------------|----------------:|
| subject_id              |   19480 | 14998472.265913758         | 10000690.0          | 12504284.5                 | 15003625.0          | 17521308.75                | 19999840.0          |     2.89105e+06 |
| hadm_id                 |   19480 | 24971986.08834702          | 20001361.0          | 22489511.5                 | 24968827.5          | 27446870.0                 | 29999098.0          |     2.87746e+06 |
| stay_id                 |   19480 | 34944378.27736139          | 30000646.0          | 32406347.0                 | 34894210.0          | 37461555.5                 | 39999858.0          |     2.90257e+06 |
| intime                  |   19480 | 2152-09-14 05:32:19.711807 | 2110-01-12 00:54:00 | 2133-01-25 13:30:45.750000 | 2152-08-28 12:00:47 | 2172-06-26 22:48:01.500000 | 2213-05-23 01:53:15 |   nan           |
| los                     |   19480 | 6.40221608701232           | 2.000115740740741   | 2.760943287037037          | 3.9594791666666667  | 7.116634837962963          | 159.66680555555556  |     6.91418     |
| admittime               |   19480 | 2152-09-13 03:45:10.943531 | 2110-01-11 22:47:00 | 2133-01-23 05:36:15        | 2152-08-25 04:46:00 | 2172-06-25 05:10:00        | 2213-05-23 01:51:00 |   nan           |
| admission_age           |   19480 | 61.055133470225876         | 18.0                | 50.0                       | 62.0                | 74.0                       | 100.0               |    17.2336      |
| target_noaf             |   19480 | 0.07669404517453798        | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 1.0                 |     0.266112    |
| hr_min                  |   19429 | 70.93289412733543          | 20.0                | 60.0                       | 69.0                | 81.0                       | 145.0               |    16.1063      |
| hr_max                  |   19429 | 104.34155128930979         | 38.0                | 90.0                       | 103.0               | 117.0                      | 223.0               |    20.0092      |
| rr_min                  |   19376 | 12.580099091659786         | 4.0                 | 10.0                       | 12.0                | 15.0                       | 33.0                |     3.65867     |
| rr_max                  |   19376 | 28.144766721717588         | 11.0                | 23.0                       | 27.0                | 32.0                       | 80.0                |     6.75911     |
| sbp_min                 |   18132 | 95.34303992940657          | 40.0                | 83.0                       | 94.0                | 108.0                      | 247.0               |    20.1401      |
| sbp_max                 |   18132 | 143.9538936686521          | 40.0                | 127.0                      | 143.0               | 159.0                      | 269.0               |    25.8021      |
| dbp_min                 |   18184 | 50.28470083589969          | 20.0                | 42.0                       | 50.0                | 59.0                       | 132.0               |    13.5672      |
| dbp_max                 |   18184 | 88.62829960404751          | 20.0                | 75.0                       | 87.0                | 100.0                      | 200.0               |    21.6         |
| mbp_min                 |   19325 | 62.06282018111255          | 30.0                | 54.0                       | 61.0                | 70.0                       | 138.0               |    12.5539      |
| mbp_max                 |   19325 | 106.80082794307891         | 44.0                | 93.0                       | 104.0               | 117.0                      | 220.0               |    20.1777      |
| temp_min                |   19172 | 36.39175533764517          | 26.666666666666668  | 36.27777777777778          | 36.5                | 36.72222222222222          | 39.8                |     0.708061    |
| temp_max                |   19172 | 37.50979124649373          | 31.6                | 37.0                       | 37.333333333333336  | 37.888888888888886         | 42.3                |     0.768423    |
| spo2_min                |   19427 | 92.03711329592835          | 41.0                | 90.0                       | 93.0                | 95.0                       | 100.0               |     5.1846      |
| fio2_max                |   10948 | 70.01150895140665          | 21.0                | 50.0                       | 60.0                | 100.0                      | 100.0               |    25.5985      |
| gcs_eye_min             |   19420 | 2.563336766220391          | 1.0                 | 1.0                        | 3.0                 | 4.0                        | 4.0                 |     1.26497     |
| gcs_verbal_min          |   19416 | 2.8324062628759785         | 1.0                 | 1.0                        | 2.0                 | 5.0                        | 5.0                 |     1.87962     |
| gcs_motor_min           |   19419 | 4.438488078685823          | 1.0                 | 3.0                        | 6.0                 | 6.0                        | 6.0                 |     2.04473     |
| weight                  |   19345 | 81.56797415352804          | 20.5                | 65.4                       | 78.1                | 93.7                       | 296.8               |    23.8876      |
| hemoglobin_min          |   19022 | 10.573940700241826         | 2.1                 | 8.8                        | 10.6                | 12.2                       | 19.3                |     2.33217     |
| hemoglobin_max          |   19022 | 11.374193039638314         | 4.1                 | 9.8                        | 11.3                | 12.8                       | 24.6                |     2.14438     |
| wbc_min                 |   19026 | 11.25432986439609          | 0.1                 | 7.2                        | 10.0                | 13.6                       | 295.2               |     7.94611     |
| wbc_max                 |   19026 | 13.669091243561441         | 0.1                 | 8.6                        | 12.0                | 16.4                       | 295.5               |     9.97668     |
| platelets_min           |   19027 | 198.70552372943712         | 5.0                 | 131.0                      | 188.0               | 250.0                      | 1297.0              |   103.537       |
| platelets_max           |   19027 | 221.87591317601303         | 8.0                 | 152.0                      | 208.0               | 273.0                      | 1418.0              |   108.781       |
| bun_min                 |   19119 | 22.609184580783513         | 1.0                 | 11.0                       | 16.0                | 27.0                       | 224.0               |    19.5993      |
| bun_max                 |   19119 | 26.029028714890945         | 1.0                 | 12.0                       | 19.0                | 31.0                       | 257.0               |    22.4675      |
| creatinine_min          |   19123 | 1.2596193065941537         | 0.1                 | 0.7                        | 0.9                 | 1.3                        | 23.6                |     1.37756     |
| creatinine_max          |   19123 | 1.4711551534801026         | 0.1                 | 0.7                        | 1.0                 | 1.5                        | 23.9                |     1.63684     |
| glucose_min             |   19128 | 122.89978042659975         | 12.0                | 97.0                       | 115.0               | 139.0                      | 519.0               |    41.9227      |
| glucose_max             |   19128 | 165.97684023421164         | 36.0                | 116.0                      | 144.0               | 187.0                      | 797.0               |    80.6834      |
| aniongap_min            |   19115 | 12.994193042113523         | 1.0                 | 11.0                       | 13.0                | 15.0                       | 49.0                |     3.56667     |
| aniongap_max            |   19115 | 15.453989013863458         | 2.0                 | 13.0                       | 15.0                | 17.0                       | 50.0                |     4.48253     |
| potassium_min           |   19143 | 3.843723554301833          | 1.5                 | 3.5                        | 3.8                 | 4.2                        | 6.6                 |     0.566234    |
| potassium_max           |   19143 | 4.416216371519615          | 2.6                 | 3.9                        | 4.3                 | 4.7                        | 10.0                |     0.779579    |
| sodium_min              |   19147 | 136.91993523789628         | 93.0                | 134.0                      | 137.0               | 140.0                      | 175.0               |     5.61328     |
| sodium_max              |   19147 | 139.77991330234502         | 107.0               | 137.0                      | 140.0               | 142.0                      | 175.0               |     5.40825     |
| calcium_min             |   18790 | 8.118467269824375          | 2.0                 | 7.6                        | 8.2                 | 8.7                        | 16.4                |     0.881916    |
| calcium_max             |   18790 | 8.539680681213412          | 4.7                 | 8.0                        | 8.5                 | 9.0                        | 19.0                |     0.809154    |
| ck_cpk_min              |    6002 | 1513.910696434522          | 6.0                 | 84.0                       | 207.0               | 720.0                      | 207680.0            |  8365.29        |
| ck_cpk_max              |    6002 | 2315.0803065644786         | 9.0                 | 94.0                       | 249.0               | 962.0                      | 285260.0            | 13089.9         |
| ck_mb_min               |    5476 | 20.130036523009498         | 1.0                 | 3.0                        | 6.0                 | 14.0                       | 484.0               |    47.634       |
| ck_mb_max               |    5476 | 30.67534331628926          | 1.0                 | 3.0                        | 7.0                 | 20.0                       | 598.0               |    71.1018      |
| ntbnp_min               |     707 | 6686.199434229137          | 9.0                 | 730.0                      | 2426.0              | 7679.0                     | 65383.0             | 10651.1         |
| ntbnp_max               |     707 | 6716.859971711457          | 9.0                 | 730.0                      | 2443.0              | 7679.0                     | 65383.0             | 10693.7         |
| pao2_min                |   12014 | 86.31954386549026          | 20.0                | 45.0                       | 73.0                | 107.0                      | 571.0               |    58.0955      |
| bilirubin_max           |   10219 | 2.265329288580096          | 0.1                 | 0.4                        | 0.7                 | 1.6                        | 50.0                |     5.03359     |
| urine_output_total      |   18914 | 1828.410923125727          | 0.0                 | 950.0                      | 1555.0              | 2400.0                     | 9930.0              |  1257.49        |
| vent_day1               |   19480 | 0.4147330595482546         | 0.0                 | 0.0                        | 0.0                 | 1.0                        | 1.0                 |     0.492689    |
| crrt_day1               |   19480 | 0.02084188911704312        | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 1.0                 |     0.142859    |
| antibiotics_day1        |   19480 | 0.5869096509240247         | 0.0                 | 0.0                        | 1.0                 | 1.0                        | 1.0                 |     0.492401    |
| max_norepinephrine_rate |   19480 | 0.08027063035595859        | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 4.979412071406841   |     0.254769    |
| max_epinephrine_rate    |   19480 | 0.004649530681675319       | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 4.963503684848547   |     0.074776    |
| max_dopamine_rate       |   19480 | 0.29543099144963236        | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 69.48953866958618   |     2.13441     |
| comorb_hypertension     |   19480 | 0.4160164271047228         | 0.0                 | 0.0                        | 0.0                 | 1.0                        | 1.0                 |     0.492909    |
| comorb_diabetes         |   19480 | 0.2596509240246407         | 0.0                 | 0.0                        | 0.0                 | 1.0                        | 1.0                 |     0.438454    |
| comorb_ckd              |   19480 | 0.14969199178644763        | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 1.0                 |     0.356778    |
| comorb_mi               |   19480 | 0.05195071868583162        | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 1.0                 |     0.221933    |
| comorb_lung             |   19480 | 0.12700205338809034        | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 1.0                 |     0.332984    |
| comorb_liver            |   19480 | 0.10451745379876796        | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 1.0                 |     0.305938    |
| comorb_alcohol          |   19480 | 0.10528747433264887        | 0.0                 | 0.0                        | 0.0                 | 0.0                        | 1.0                 |     0.306931    |

## Harmonise demographics

In [128]:
def harmonize_demographics(df):
  race_map = {
    'WHITE': 'White', 'WHITE - OTHER EUROPEAN': 'White', 'WHITE - RUSSIAN': 'White', 
    'WHITE - EASTERN EUROPEAN': 'White', 'WHITE - BRAZILIAN': 'White', 'PORTUGUESE': 'White',
    
    'BLACK/AFRICAN AMERICAN': 'Black', 'BLACK/CARIBBEAN ISLAND': 'Black', 
    'BLACK/CAPE VERDEAN': 'Black', 'BLACK/AFRICAN': 'Black',
    
    'ASIAN': 'Asian', 'ASIAN - CHINESE': 'Asian', 'ASIAN - SOUTH EAST ASIAN': 'Asian', 
    'ASIAN - ASIAN INDIAN': 'Asian', 'ASIAN - KOREAN': 'Asian',
    
    'HISPANIC/LATINO - PUERTO RICAN': 'Hispanic', 'HISPANIC/LATINO - DOMINICAN': 'Hispanic', 
    'HISPANIC OR LATINO': 'Hispanic', 'HISPANIC/LATINO - GUATEMALAN': 'Hispanic', 
    'HISPANIC/LATINO - SALVADORAN': 'Hispanic', 'HISPANIC/LATINO - MEXICAN': 'Hispanic', 
    'HISPANIC/LATINO - HONDURAN': 'Hispanic', 'HISPANIC/LATINO - CENTRAL AMERICAN': 'Hispanic', 
    'HISPANIC/LATINO - COLUMBIAN': 'Hispanic', 'HISPANIC/LATINO - CUBAN': 'Hispanic',
    'SOUTH AMERICAN': 'Hispanic',
  }
  
  # Map matching text; classify sparse or undisclosed tracks as 'Other/Unknown'
  df['race_group'] = df['race'].map(race_map).fillna('Other/Unknown')
  
  # Convert sensitive categoricals to clean reference strings
  df['gender'] = df['gender'].map({'M': 'Male', 'F': 'Female'})
  
  return df

dataset = harmonize_demographics(dataset)
print(dataset.groupby(['race_group'])["target_noaf"].value_counts())

race_group     target_noaf
Asian          0                580
               1                 44
Black          0               1946
               1                 80
Hispanic       0                771
               1                 25
Other/Unknown  0               3839
               1                331
White          0              10850
               1               1014
Name: count, dtype: int64

## SOFA

In [129]:
def calculate_sofa(df):
  sofa_df = df.copy()

  # RESPIRATORY SYSTEM
  fio2_fraction = sofa_df['fio2_max'] / 100.0
  pf_ratio = sofa_df['pao2_min'] / fio2_fraction
  sf_ratio = sofa_df['spo2_min'] / fio2_fraction
  resp_ratio = pf_ratio.fillna(sf_ratio)
  is_vented = sofa_df['vent_day1'] == 1

  resp_conds = [
    (resp_ratio <= 100) & is_vented,
    (resp_ratio <= 200) & is_vented,
    (resp_ratio <= 300),
    (resp_ratio <= 400),
    (resp_ratio > 400) | resp_ratio.isna()
  ]
  resp_choices = [4, 3, 2, 1, 0]
  sofa_df['sofa_respiratory'] = np.select(resp_conds, resp_choices, default=0)

  # COAGULATION
  coag_conds = [
    (sofa_df['platelets_min'] <= 20),
    (sofa_df['platelets_min'] <= 50),
    (sofa_df['platelets_min'] <= 100),
    (sofa_df['platelets_min'] <= 150),
    (sofa_df['platelets_min'] > 150) | sofa_df['platelets_min'].isna()
  ]
  coag_choices = [4, 3, 2, 1, 0]
  sofa_df['sofa_coagulation'] = np.select(coag_conds, coag_choices, default=0)

  # LIVER
  liver_conds = [
    (sofa_df['bilirubin_max'] >= 12.0),
    (sofa_df['bilirubin_max'] >= 6.0) & (sofa_df['bilirubin_max'] < 12.0),
    (sofa_df['bilirubin_max'] >= 2.0) & (sofa_df['bilirubin_max'] < 6.0),
    (sofa_df['bilirubin_max'] >= 1.2) & (sofa_df['bilirubin_max'] < 2.0),
    (sofa_df['bilirubin_max'] < 1.2) | sofa_df['bilirubin_max'].isna()
  ]
  liver_choices = [4, 3, 2, 1, 0]
  sofa_df['sofa_liver'] = np.select(liver_conds, liver_choices, default=0)

  # CARDIOVASCULAR SYSTEM
  cardio_conds = [
    # Score 4: High dose vasopressor rates
    (sofa_df['max_dopamine_rate'] > 15.0) | 
    (sofa_df['max_epinephrine_rate'] > 0.1) | 
    (sofa_df['max_norepinephrine_rate'] > 0.1),
    
    # Score 3: Moderate dose vasopressor rates
    (sofa_df['max_dopamine_rate'] > 5.0) | 
    ((sofa_df['max_epinephrine_rate'] > 0.0) & (sofa_df['max_epinephrine_rate'] <= 0.1)) | 
    ((sofa_df['max_norepinephrine_rate'] > 0.0) & (sofa_df['max_norepinephrine_rate'] <= 0.1)),
    
    # Score 2: Low dose dopamine or presence of dobutamine proxy
    (sofa_df['max_dopamine_rate'] > 0.0) & (sofa_df['max_dopamine_rate'] <= 5.0),
    
    # Score 1: Mean Blood Pressure hypotension under 70 mmHg (without vasopressors)
    (sofa_df['mbp_min'] < 70.0),
    
    # Score 0: Stable hemodynamics
    (sofa_df['mbp_min'] >= 70.0) | sofa_df['mbp_min'].isna()
  ]
  cardio_choices = [4, 3, 2, 1, 0]
  sofa_df['sofa_cardiovascular'] = np.select(cardio_conds, cardio_choices, default=0)

  # CENTRAL NERVOUS SYSTEM
  # Glasgow Coma Scale
  gcs_total = sofa_df['gcs_eye_min'] + sofa_df['gcs_verbal_min'] + sofa_df['gcs_motor_min']
    
  cns_conds = [
    (gcs_total < 6),
    (gcs_total >= 6) & (gcs_total <= 9),
    (gcs_total >= 10) & (gcs_total <= 12),
    (gcs_total >= 13) & (gcs_total <= 14),
    (gcs_total == 15) | gcs_total.isna()
  ]
  cns_choices = [4, 3, 2, 1, 0]
  sofa_df['sofa_cns'] = np.select(cns_conds, cns_choices, default=0)

  # RENAL SYSTEM
  # Compute Creatinine Path
  creat_conds = [
    (sofa_df['creatinine_max'] >= 5.0),
    (sofa_df['creatinine_max'] >= 3.5) & (sofa_df['creatinine_max'] < 5.0),
    (sofa_df['creatinine_max'] >= 2.0) & (sofa_df['creatinine_max'] < 3.5),
    (sofa_df['creatinine_max'] >= 1.2) & (sofa_df['creatinine_max'] < 2.0),
    (sofa_df['creatinine_max'] < 1.2) | sofa_df['creatinine_max'].isna()
  ]
  creat_choices = [4, 3, 2, 1, 0]
  score_creat = np.select(creat_conds, creat_choices, default=0)
  
  # Compute Urine Output Path
  urine_conds = [
    (sofa_df['urine_output_total'] < 200.0),
    (sofa_df['urine_output_total'] < 500.0),
    (sofa_df['urine_output_total'] >= 500.0) | sofa_df['urine_output_total'].isna()
  ]
  urine_choices = [4, 3, 0]
  score_urine = np.select(urine_conds, urine_choices, default=0)

  sofa_df['sofa_renal'] = np.maximum(score_creat, score_urine)

  # TOTAL SCORE
  sofa_df['sofa_total'] = (
    sofa_df['sofa_respiratory'] + 
    sofa_df['sofa_coagulation'] + 
    sofa_df['sofa_liver'] + 
    sofa_df['sofa_cardiovascular'] + 
    sofa_df['sofa_cns'] + 
    sofa_df['sofa_renal']
  )

  return sofa_df

dataset = calculate_sofa(dataset)
print(dataset[['sofa_total', 'sofa_respiratory', 'sofa_cardiovascular']].describe())

         sofa_total  sofa_respiratory  sofa_cardiovascular
count  19480.000000      19480.000000         19480.000000
mean       6.595431          1.530852             1.443429
std        4.583772          1.575250             1.408569
min        0.000000          0.000000             0.000000
25%        3.000000          0.000000             1.000000
50%        6.000000          2.000000             1.000000
75%       10.000000          3.000000             1.000000
max       24.000000          4.000000             4.000000

# TRAINING and TEST samplings

In [134]:
# Filter race groups to keep viable population
cohort_filtered = dataset[dataset['race_group'].isin(['White', 'Black'])].copy()
race_integer_map = {'White': 1, 'Black': 0}
cohort_filtered['race_group'] = cohort_filtered['race_group'].map(race_integer_map).astype(int)

# Target and sensitive attribute
target_col = 'target_noaf'
sens_col = 'race_group'

# Metadata columns
metadata_cols = ['subject_id', 'hadm_id', 'stay_id', 'intime', 'los', 'admittime', 'race']

features = [col for col in cohort_filtered.columns
  if col not in metadata_cols + [sens_col, target_col]]

print(f"Total Cohort Size (White + Black): {cohort_filtered.shape[0]}")
print(f"Number of clinical predictive features extracted: {len(features)}")

Total Cohort Size (White + Black): 13890
Number of clinical predictive features extracted: 69

In [135]:
from sklearn.model_selection import train_test_split

cohort_filtered['strata'] = (
  cohort_filtered['race_group'].astype(str) + "_" +
  cohort_filtered[target_col].astype(str)
)

train_df, test_df = train_test_split(
  cohort_filtered, 
  test_size=TEST_SIZE, 
  stratify=cohort_filtered['strata'], 
  random_state=SEED
)

train_df = train_df.drop(columns=(['strata'] + metadata_cols))
test_df = test_df.drop(columns=(['strata'] + metadata_cols))

In [136]:
print("="*60)
print(f"TRAIN COLORT SHAPE: {train_df.shape[0]} rows | TEST COHORT SHAPE: {test_df.shape[0]} rows")
print("="*60)

print("\n[1] TARGET DISTRIBUTION PARITY (target_noaf)")
print("--- Training Split ---")
print(train_df[target_col].value_counts(normalize=True))
print("--- Testing Split ---")
print(test_df[target_col].value_counts(normalize=True))

print("\n[2] PROTECTED ATTRIBUTE PARITY (race_group)")
print("--- Training Split ---")
print(train_df['race_group'].value_counts(normalize=True))
print("--- Testing Split ---")
print(test_df['race_group'].value_counts(normalize=True))

print("\n[3] JOINT TARGET-DEMOGRAPHIC RECONSTRUCTION CHECK (Raw Counts)")
print("--- Training Split Sub-Matrix ---")
print(pd.crosstab(train_df['race_group'], train_df[target_col]))
print("--- Testing Split Sub-Matrix ---")
print(pd.crosstab(test_df['race_group'], test_df[target_col]))
print("="*60)

============================================================
TRAIN COLORT SHAPE: 11112 rows | TEST COHORT SHAPE: 2778 rows
============================================================

[1] TARGET DISTRIBUTION PARITY (target_noaf)
--- Training Split ---
target_noaf
0    0.921256
1    0.078744
Name: proportion, dtype: float64
--- Testing Split ---
target_noaf
0    0.921166
1    0.078834
Name: proportion, dtype: float64

[2] PROTECTED ATTRIBUTE PARITY (race_group)
--- Training Split ---
race_group
1    0.854122
0    0.145878
Name: proportion, dtype: float64
--- Testing Split ---
race_group
1    0.854212
0    0.145788
Name: proportion, dtype: float64

[3] JOINT TARGET-DEMOGRAPHIC RECONSTRUCTION CHECK (Raw Counts)
--- Training Split Sub-Matrix ---
target_noaf     0    1
race_group
0            1557   64
1            8680  811
--- Testing Split Sub-Matrix ---
target_noaf     0    1
race_group
0             389   16
1            2170  203
============================================================

In [138]:
train_df.info()

<class 'pandas.DataFrame'>
Index: 11112 entries, 14196 to 18039
Data columns (total 71 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   11112 non-null  str
 1   admission_age            11112 non-null  int64
 2   target_noaf              11112 non-null  int32
 3   hr_min                   11079 non-null  float64
 4   hr_max                   11079 non-null  float64
 5   rr_min                   11046 non-null  float64
 6   rr_max                   11046 non-null  float64
 7   sbp_min                  10360 non-null  float64
 8   sbp_max                  10360 non-null  float64
 9   dbp_min                  10387 non-null  float64
 10  dbp_max                  10387 non-null  float64
 11  mbp_min                  11025 non-null  float64
 12  mbp_max                  11025 non-null  float64
 13  temp_min                 10956 non-null  float64
 14  temp_max                 10956 non-null  float64
 15  spo2_min                 11077 non-null  float64
 16  fio2_max                 5855 non-null   float64
 17  gcs_eye_min              11072 non-null  float64
 18  gcs_verbal_min           11068 non-null  float64
 19  gcs_motor_min            11070 non-null  float64
 20  weight                   11028 non-null  float64
 21  hemoglobin_min           10823 non-null  float64
 22  hemoglobin_max           10823 non-null  float64
 23  wbc_min                  10824 non-null  float64
 24  wbc_max                  10824 non-null  float64
 25  platelets_min            10826 non-null  float64
 26  platelets_max            10826 non-null  float64
 27  bun_min                  10893 non-null  float64
 28  bun_max                  10893 non-null  float64
 29  creatinine_min           10892 non-null  float64
 30  creatinine_max           10892 non-null  float64
 31  glucose_min              10895 non-null  float64
 32  glucose_max              10895 non-null  float64
 33  aniongap_min             10889 non-null  float64
 34  aniongap_max             10889 non-null  float64
 35  potassium_min            10904 non-null  float64
 36  potassium_max            10904 non-null  float64
 37  sodium_min               10908 non-null  float64
 38  sodium_max               10908 non-null  float64
 39  calcium_min              10679 non-null  float64
 40  calcium_max              10679 non-null  float64
 41  ck_cpk_min               3300 non-null   float64
 42  ck_cpk_max               3300 non-null   float64
 43  ck_mb_min                3032 non-null   float64
 44  ck_mb_max                3032 non-null   float64
 45  ntbnp_min                380 non-null    float64
 46  ntbnp_max                380 non-null    float64
 47  pao2_min                 6599 non-null   float64
 48  bilirubin_max            5620 non-null   float64
 49  urine_output_total       10758 non-null  float64
 50  vent_day1                11112 non-null  int32
 51  crrt_day1                11112 non-null  int32
 52  antibiotics_day1         11112 non-null  int32
 53  max_norepinephrine_rate  11112 non-null  float64
 54  max_epinephrine_rate     11112 non-null  float64
 55  max_dopamine_rate        11112 non-null  float64
 56  comorb_hypertension      11112 non-null  int64
 57  comorb_diabetes          11112 non-null  int64
 58  comorb_ckd               11112 non-null  int64
 59  comorb_mi                11112 non-null  int64
 60  comorb_lung              11112 non-null  int64
 61  comorb_liver             11112 non-null  int64
 62  comorb_alcohol           11112 non-null  int64
 63  race_group               11112 non-null  int64
 64  sofa_respiratory         11112 non-null  int64
 65  sofa_coagulation         11112 non-null  int64
 66  sofa_liver               11112 non-null  int64
 67  sofa_cardiovascular      11112 non-null  int64
 68  sofa_cns                 11112 non-null  int64
 69  sofa_renal               11112 non-null  int64
 70  sofa_total               11112 non-null  int64
dtypes: float64(50), int32(4), int64(16), str(1)
memory usage: 6.2 MB